title: CV | Miguel Nunez
description:  A Mechanical Engineer.
url: https://ergocreate.github.io/miguel-nunez-cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
